### PR TITLE
Email

### PR DESCRIPTION
**Pull request by denesnori**

### CODE REVIEW

**Comment by denesnori** [comment]
So update what I have done so far:
- fixed FormEmail... i had to add these lines to webpack config 
```
  resolve: {
        alias: {
            "react/lib/DOMProperty": "react-dom/lib/DOMProperty"
        }
    }
```
- looked into options how to send emails from the backend...tried to use, react-html-email and mailchimp and courier js based on this [article](https://medium.com/readme-mic/creating-and-sending-reusable-emails-with-react-a80ade7614b#.eneadoaim) --> always got error from courier js, so i looked into other options
- nodemailer + mailgun : registered on mailgun with our childline gmail address. I didn't verify our website (since i can't) so we can online send mails to childline.report.content@gmail.com. I think it is fine for us :). 
Steps:
- setup the email sending function on the backend (without a route)..it run every time the server started . Emails were received on our gmail account.
- setup a /email post route on the backend
- set up porst request on the frontend...When we hit submit the data is sent to the backend
- setup waterfall (since submit saves, the utl and the description, and send the data to the backend, so its important that we only send the data, after it has been saved!)

**Comment by denesnori** [comment]
Next steps: 
- I'll get rid of FormEmail
nodemailerMailgun's options object can handle html tags, so we can format our email on the backend
```
{
    from: 'postmaster@childline-yoti.com',
    to: 'childline.report.content@gmail.com', // An array if you have multiple recipients.
    subject: 'Report online content',
    html: `<h1>${req.body.imageCriteria}</h1><br><h2>${req.body.url}</h2><br><h3>${req.body.description}</h3>`
  }
```

**Comment by denesnori** [comment]
one more thing: 
- I updated the add imagedescription function, since it used to concatenate the text to the array on every click

However, it is not the behaviour we want:
1, the checkbox is ticked---> add the data to the array
2. the same checkbox clicked again (it is unchecked now) --> remove the string from the Array 
3, the same checkbox is clicked again (it is checked now) --> add the string to the array

**Comment by SavageWilliam** [comment]
@denesnori Looks great. My week starts again tomorrow. I'm starting Node week with FAC1NAZ, so my Monday & Tuesday might be busy!

**Pull request merged**
